/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_bpg_client_DecoderWrapper */

#ifndef _Included_com_example_android_bpg_client_DecoderWrapper
#define _Included_com_example_android_bpg_client_DecoderWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_bpg_client_DecoderWrapper
 * Method:    fetchDecodedBufferSize
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_1bpg_1client_DecoderWrapper_fetchDecodedBufferSize
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_example_android_bpg_client_DecoderWrapper
 * Method:    decodeBuffer
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_1bpg_1client_DecoderWrapper_decodeBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
